spring:
  application:
    name: tas-query-poc
    
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
      schema: tas_demo
      
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: tas_demo
    hibernate:
      ddl-auto: none
    show-sql: true
    
  # AI configuration for SQL generation with SQLCoder
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: sqlcoder:7b  # Best model for SQL generation
        options:
          temperature: 0.0  # Deterministic output for consistent SQL
          top-k: 10
          top-p: 0.9
          num-predict: 500
          num-threads: 8    # Adjust based on your CPU
          
  thymeleaf:
    cache: false
    
server:
  port: 8080
  
logging:
  level:
    com.tas.poc: DEBUG
    
# Application specific properties
tas:
  conversation:
    history-size: 5
    session-timeout-minutes: 30